[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
via_ir = true
fs_permissions = [{ access = "read", path = "./config/networks.json"}]
always_use_create_2_factory = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
