[package]
name = "appchain-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "appchain_core"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140" 