[solana]
devnet_url = "https://api.devnet.solana.com"
mainnet_url = "https://api.devnet.solana.com"
default_url = "https://api.devnet.solana.com"

[grpc]
address = "127.0.0.1:50052"

[storage]
redis_url = "redis://127.0.0.1/"
