[package]
name = "token_holders"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
ethers = "2.0.14"
tokio = { version = "1.44.1", features = ["full"] }
